services:
  frontend:
    image: nginx:alpine
    volumes: 
      - ./frontend:/usr/share/nginx/html

  backend:
    image: backend
    container_name: backend
    build: ./backend
    command: sh -c "npm install && npm run dev"
    environment:
      - PGDATABASE=${DB_DATABASE}
      - PGUSER=${DB_USER}
      - PGPASSWORD=${DB_PASSWORD}
      - PGHOST=database
    volumes:
      - ./backend:/backend

  database:
    image: database
    container_name: database
    build: ./db
    ports:
     - 5434:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_HOST=${DB_HOST}

  proxy:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend

volumes:
  db_data:
