version: '3'

services:
  frontend:
    image: nginx:alpine
    volumes: 
      - ./frontend:/usr/share/nginx/html

  backend:
    image: backend
    container_name: backend
    build: ./backend
    command: sh -c "npm install && npm run dev"
    environment:
      - PG_DATABASE=${DB_DATABASE}
      - PG_USER=${DB_USER}
      - PG_PASSWORD=${DB_PASSWORD}
      - PG_HOST=database
    volumes:
      - ./backend:/backend

  database:
    image: database
    container_name: database
    build: ./db
    ports:
     - 5434:5432
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  proxy:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
